### ISSUE TITLE
change of speaker for London

### ISSUE THREAD

**Issue by morsej123** [FPSAC/FPSAC.github.io#2]
Kristina Vuskovic should replace Maria on the permanent page.  I tried to fix it, but now I can't eve access the page and worry I've done real damage!  The page I worked on is: http://fpsac.org/confs/fpsac-2017/

**Comment by nthiery** [comment]
Fixed :-)

**Comment by nthiery** [comment]
Oh, and in general, don't worry about breaking stuff. Everything is safely version controlled, and it's always easy to rollback. I.e. you can temporarilly break how it things are rendered, but the underlying data is always safe.
