### ISSUE TITLE
How to add new poster thumbnail

### ISSUE THREAD

**Issue by stumpc5** [FPSAC/FPSAC.github.io#4]
I did not see how to compile a new thumbnail for fpsac poster 2020, @nthiery could you have a look -- thanks!

**Comment by nthiery** [comment]
Hi Christian!

> I did not see how to compile a new thumbnail for fpsac poster 2020,
> @nthiery could you have a look -- thanks!

Yeah, so far I did it myself, so it did not get documented. Here it is:

- add the original jpeg or pdf in public/.

- from the root directory, type:

        make thumbnails

- add, commit and push the files

- specify the image file name in the _confs/fpsac-... file

Cheers,

**Comment by stumpc5** [comment]
Thanks and pushed! Am I just overseeing it or are the posters not downloadable on the page?=

**Comment by nthiery** [comment]
Good point. That would be a good feature to have. Easy to implement,
but not sure what's the most natural approach given that we use
clicking on the poster to go to the page. Maybe a "download poster
link" somewhere.

**Comment by stumpc5** [comment]
Well, there is the poster also on the top right corner of the conf details page. And this links to the page itself. So replacing this link with a link to the download should do the job, shouldn't it?

**Comment by nthiery** [comment]
> Well, there is the poster also on the top right corner of the conf
> details page. And this links to the page itself. So replacing this
> link with a link to the download should do the job, shouldn't it?

Yeah, that's redundant indeed. Go for it!

**Comment by stumpc5** [comment]
done

**Comment by nthiery** [comment]
Thanks! Much better indeed.
